In [1]:
import numpy as np

In [6]:
game = np.zeros((9,9))

In [9]:
game

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
game[1][2] = 1

In [11]:
np.arange(25).reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
game = [[0, 9, 6, 0, 4, 0, 0, 3, 0],
        [0, 5, 7, 8, 2, 0, 0, 0, 0],
        [1, 0, 0, 9, 0, 0, 5, 0, 0],
        [0, 0, 9, 0, 1, 0, 0, 0, 8],
        [5, 0, 0, 0, 0, 0, 0, 0, 2],
        [4, 0, 0, 0, 9, 0, 6, 0, 0],
        [0, 0, 4, 0, 0, 3, 0, 0, 1],
        [0, 0, 0, 0, 7, 9, 2, 6, 0],
        [0, 2, 0, 0, 5, 0, 9, 8, 0]];

In [22]:
npGame = np.array(game)
npGame

array([[0, 9, 6, 0, 4, 0, 0, 3, 0],
       [0, 5, 7, 8, 2, 0, 0, 0, 0],
       [1, 0, 0, 9, 0, 0, 5, 0, 0],
       [0, 0, 9, 0, 1, 0, 0, 0, 8],
       [5, 0, 0, 0, 0, 0, 0, 0, 2],
       [4, 0, 0, 0, 9, 0, 6, 0, 0],
       [0, 0, 4, 0, 0, 3, 0, 0, 1],
       [0, 0, 0, 0, 7, 9, 2, 6, 0],
       [0, 2, 0, 0, 5, 0, 9, 8, 0]])

In [20]:
np.array(game)[:,0]

array([0, 0, 1, 0, 5, 4, 0, 0, 0])

In [21]:
np.array(game)[0,:]

array([0, 9, 6, 0, 4, 0, 0, 3, 0])

In [31]:
def search(x, y):
    xAxis = npGame[y,:]
    yAxis = npGame[:,x]
    box = np.zeros((3, 3))
    print(xAxis)
    print(yAxis)
    print(box)

In [34]:
def getBoxXY(x, y):
    return 1, 2

In [35]:
def getBox(x, y):
    boxX, boxY = getBoxXY(x, y)
    print()

In [30]:
search(2,3)

[0 0 9 0 1 0 0 0 8]
[6 7 0 9 0 0 4 0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
npGame[0:4:3, 0:4:3]

array([[0, 0],
       [0, 0]])

In [44]:
npGame[np.ix_([0,1],[0,3])]

array([[0, 0],
       [0, 0]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])